name: tessera
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - rasterio
  - fiona
  - jupyterlab
  - geemap
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - voila
  - ipykernel